#!/bin/bash

#name: neo4j
#short: Build and deploy the Neo4J database to the local cluster

cd "$REPO_BASE" || exit

# Source the .env file
source .env
env | grep HTTP

kubectl config use-context k3d-k3s-default
kubectl config set-context --current --namespace=playground


helm repo add neo4j https://helm.neo4j.com/neo4j
helm repo update

helm uninstall neo4j || true
sleep 5



cd "$REPO_BASE" || exit

# redeploy
cd deploy/apps/neo4j || exit

# Delete a persistent volume claim for Neo4J
kubectl delete -f ./pvc.yaml

# Create a persistent volume claim for Neo4J
kubectl apply -f ./pvc.yaml

echo "Deploying Neo4J helm chart with the following values:"

helm install neo4j -n playground neo4j/neo4j  \
    -f ./values.yaml
