apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
      - name: graphql
        image: k3d-registry.localhost:5500/graphql-server:local
        imagePullPolicy: Always
        ports:
        - containerPort: 8501  # HTTP Port
        - containerPort: 8502  # WebSocket Port
        envFrom:
        - secretRef:
            name: graphql-secrets
      imagePullSecrets:
        - name: playground-image-pull-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  namespace: playground
spec:
  selector:
    app: graphql
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: websocket
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
